apiVersion: v1
kind: Service
metadata:
  name: postgres-master-service
  namespace: postgres-ns
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: postgres
    role: master


---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replica-service
  namespace: postgres-ns
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: postgres
    role: replica
