apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: django-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-app
        image: mradulnatani/django-webtool
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: postgres-secret
        - secretRef:
            name: django-secrets
        env:
        - name: DATABASE_HOST
          value: "ca-postgres-cluster-rw.postgres-ns.svc.cluster.local"
        - name: DATABASE_NAME
          value: "cadatabase"
        - name: DEBUG
          value: "False"
