global:
  name: consul
  acls:
    manageSystemACLs: true
  gossipEncryption:
    autoGenerate: true
  enablePodSecurityPolicies: false

server:
  enabled: true
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "400m"

client:
  enabled: true
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

ui:
  enabled: true

connectInject:
  enabled: true
  default: true

controller:
  enabled: true

